#!/usr/bin/python2
# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(450, 40, 91, 139))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.ScanTimeLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.ScanTimeLayout.setObjectName(_fromUtf8("ScanTimeLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cantarell"))
        font.setPointSize(12)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.ScanTimeLayout.addWidget(self.label)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.rbWide3 = QtGui.QRadioButton(self.layoutWidget)
        self.rbWide3.setObjectName(_fromUtf8("rbWide3"))
        self.verticalLayout.addWidget(self.rbWide3)
        self.rbWide6 = QtGui.QRadioButton(self.layoutWidget)
        self.rbWide6.setObjectName(_fromUtf8("rbWide6"))
        self.verticalLayout.addWidget(self.rbWide6)
        self.rbNorm12 = QtGui.QRadioButton(self.layoutWidget)
        self.rbNorm12.setChecked(True)
        self.rbNorm12.setObjectName(_fromUtf8("rbNorm12"))
        self.verticalLayout.addWidget(self.rbNorm12)
        self.rbNarr60 = QtGui.QRadioButton(self.layoutWidget)
        self.rbNarr60.setObjectName(_fromUtf8("rbNarr60"))
        self.verticalLayout.addWidget(self.rbNarr60)
        self.ScanTimeLayout.addLayout(self.verticalLayout)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(440, 200, 125, 110))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.MultiplerLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.MultiplerLayout.setObjectName(_fromUtf8("MultiplerLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.MultiplerLayout.addWidget(self.label_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.radioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout_3.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.verticalLayout_3.addWidget(self.radioButton_3)
        self.MultiplerLayout.addLayout(self.verticalLayout_3)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(580, 80, 124, 138))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.ChartExpansionLayout = QtGui.QVBoxLayout()
        self.ChartExpansionLayout.setObjectName(_fromUtf8("ChartExpansionLayout"))
        self.radioButton_4 = QtGui.QRadioButton(self.widget)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.ChartExpansionLayout.addWidget(self.radioButton_4)
        self.radioButton_5 = QtGui.QRadioButton(self.widget)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.ChartExpansionLayout.addWidget(self.radioButton_5)
        self.radioButton_6 = QtGui.QRadioButton(self.widget)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.ChartExpansionLayout.addWidget(self.radioButton_6)
        self.radioButton_7 = QtGui.QRadioButton(self.widget)
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.ChartExpansionLayout.addWidget(self.radioButton_7)
        self.verticalLayout_4.addLayout(self.ChartExpansionLayout)
        self.widget1 = QtGui.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(580, 240, 113, 83))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.TimeDrive = QtGui.QCheckBox(self.widget1)
        self.TimeDrive.setObjectName(_fromUtf8("TimeDrive"))
        self.verticalLayout_5.addWidget(self.TimeDrive)
        self.Index = QtGui.QCheckBox(self.widget1)
        self.Index.setObjectName(_fromUtf8("Index"))
        self.verticalLayout_5.addWidget(self.Index)
        self.checkBox = QtGui.QCheckBox(self.widget1)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_5.addWidget(self.checkBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Scan Time ", None))
        self.rbWide3.setText(_translate("MainWindow", "Widest", None))
        self.rbWide6.setText(_translate("MainWindow", "Wide", None))
        self.rbNorm12.setText(_translate("MainWindow", "Norm", None))
        self.rbNarr60.setText(_translate("MainWindow", "Narrow", None))
        self.label_2.setText(_translate("MainWindow", "Multiler", None))
        self.radioButton.setText(_translate("MainWindow", "1 (1)", None))
        self.radioButton_2.setText(_translate("MainWindow", "4 (1/2)", None))
        self.radioButton_3.setText(_translate("MainWindow", "16 (1/4)", None))
        self.label_3.setText(_translate("MainWindow", "Chart expansion", None))
        self.radioButton_4.setText(_translate("MainWindow", "0.5", None))
        self.radioButton_5.setText(_translate("MainWindow", "1.0", None))
        self.radioButton_6.setText(_translate("MainWindow", "5.0", None))
        self.radioButton_7.setText(_translate("MainWindow", "20.0", None))
        self.TimeDrive.setText(_translate("MainWindow", "Time Drive", None))
        self.Index.setText(_translate("MainWindow", "Index", None))
        self.checkBox.setText(_translate("MainWindow", "Abs", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

